const DATA = {
  nama: "Kangsad01",
  githubs: ["Kangsad01", "sadteams"],
  role: ["WhatsApp Bot Developer", "Backend Engineer", "Automation Expert"],
  about: "Aku suka bikin bot dan tools yang bener-bener dipake orang. Fokus di automation, database, dan UI yang clean.",
  foto: "https://avatars.githubusercontent.com/Kangsad01",
  email: "drakblue3@gmail.com",
  websiteScreenshot: "https://avatars.githubusercontent.com/Kangsad01",
  music: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3",
  stats: [{number: 20, label: "Repositories"}, {number: 3, label: "Years Coding"}, {number: 100, label: "Bot Users"}],
  tech: [
    {name: "Node.js", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nodejs/nodejs-original.svg"},
    {name: "MongoDB", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mongodb/mongodb-original.svg"},
    {name: "JavaScript", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-original.svg"},
    {name: "WhatsApp", icon: "https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/whatsapp.svg"}
  ]
}

let particlesArray = [];
let mouse = {x: null, y: null, radius: 150};

function getCSSVar(name){ return getComputedStyle(document.documentElement).getPropertyValue(name).trim(); }
function initTheme(){ const saved = localStorage.getItem('theme') || 'dark'; document.documentElement.setAttribute('data-theme', saved); }
function themeToggle(){ const btn = document.createElement('button'); btn.className = 'theme-toggle'; btn.innerHTML = localStorage.getItem('theme') === 'light'? '☀️' : '🌙'; document.body.appendChild(btn); btn.onclick = function(){ const html = document.documentElement; const newTheme = html.getAttribute('data-theme') === 'dark'? 'light' : 'dark'; html.setAttribute('data-theme', newTheme); localStorage.setItem('theme', newTheme); btn.innerHTML = newTheme === 'light'? '☀️' : '🌙'; } }
function autoMusic(){ const audio = new Audio(DATA.music); audio.loop = true; audio.volume = 0.08; document.body.addEventListener('click', () => { audio.play().catch(()=>{}) }, {once:true}); }
function mouseGlow(){ const glow = document.createElement('div'); glow.id='glow'; glow.style.cssText='position:fixed;width:500px;height:500px;border-radius:50%;background:radial-gradient(circle,rgba(56,189,248,0.2)0%,transparent 70%);pointer-events:none;z-index:1'; document.body.appendChild(glow); document.addEventListener('mousemove', e => { glow.style.left = (e.clientX - 250) + 'px'; glow.style.top = (e.clientY - 250) + 'px'; }) }
function scrollProgress(){ const progressBar = document.createElement('div'); progressBar.id='progress-bar'; document.body.appendChild(progressBar); window.addEventListener('scroll', () => { const winScroll = document.documentElement.scrollTop; const height = document.documentElement.scrollHeight - document.documentElement.clientHeight; progressBar.style.width = (winScroll / height) * 100 + '%'; }) }
function backToTop(){ const btn = document.createElement('button'); btn.id='back-to-top'; btn.innerHTML='↑'; document.body.appendChild(btn); window.addEventListener('scroll', () => { if(window.scrollY > 500){ btn.classList.add('show') } else{ btn.classList.remove('show') } }); btn.onclick = () => { window.scrollTo({top:0, behavior:'smooth'}) }; }
function magneticButtons(){ document.querySelectorAll('.magnetic-btn').forEach(btn => { btn.addEventListener('mousemove', e => { const rect = btn.getBoundingClientRect(); const x = e.clientX - rect.left - rect.width/2; const y = e.clientY - rect.top - rect.height/2; btn.style.transform = `translate(${x*0.3}px, ${y*0.3}px) scale(1.05)`; }); btn.addEventListener('mouseleave', () => { btn.style.transform = 'translate(0,0) scale(1)' }); }) }
function terminalType(){ const lines = ['git clone https://github.com/Kangsad01','npm install','Server running on port 3000','Portfolio loaded ✓']; const el = document.getElementById('terminal-text'); if(!el) return; let i=0, j=0; function type(){ if(j < lines[i].length){ el.innerHTML += lines[i][j++]; setTimeout(type, 40); } else { el.innerHTML += '<br>'; i++; j=0; if(i < lines.length) setTimeout(type, 600); } } type(); }
function liquidBackground(){ const canvas = document.createElement('canvas'); canvas.id='liquid-bg'; document.body.appendChild(canvas); const ctx = canvas.getContext('2d'); canvas.width=window.innerWidth; canvas.height=window.innerHeight; window.addEventListener('resize', ()=>{canvas.width=window.innerWidth; canvas.height=window.innerHeight}); function animate(){ const bgColor = getCSSVar('--bg'); ctx.clearRect(0,0,canvas.width,canvas.height); const gradient = ctx.createRadialGradient(canvas.width/2, canvas.height/2, 0, canvas.width/2, canvas.height/2, canvas.width); gradient.addColorStop(0,'rgba(56,189,248,0.1)'); gradient.addColorStop(1, bgColor); ctx.fillStyle = gradient; ctx.fillRect(0,0,canvas.width,canvas.height); requestAnimationFrame(animate); } animate(); }
function particleBackground(){ const canvas = document.createElement('canvas'); canvas.id = 'particles'; document.body.appendChild(canvas); const ctx = canvas.getContext('2d'); function resize(){ canvas.width = window.innerWidth; canvas.height = window.innerHeight; } resize(); window.addEventListener('resize', resize); for(let i = 0; i < 120; i++){ particlesArray.push({ x: Math.random() * canvas.width, y: Math.random() * canvas.height, size: Math.random() * 3 + 1, speedX: Math.random() * 0.6 - 0.3, speedY: Math.random() * 0.6 - 0.3 }) } window.addEventListener('mousemove', e => {mouse.x = e.x; mouse.y = e.y}); function animate(){ ctx.clearRect(0, 0, canvas.width, canvas.height); particlesArray.forEach(p => { const dx = mouse.x - p.x; const dy = mouse.y - p.y; const dist = Math.sqrt(dx*dx + dy*dy); if(dist < mouse.radius){ p.x -= dx/dist * 2; p.y -= dy/dist * 2; } p.x += p.speedX; p.y += p.speedY; if(p.x < 0 || p.x > canvas.width) p.speedX *= -1; if(p.y < 0 || p.y > canvas.height) p.speedY *= -1; ctx.beginPath(); ctx.arc(p.x, p.y, p.size, 0, Math.PI * 2); ctx.fillStyle = 'rgba(56,189,248,0.5)'; ctx.fill(); }); requestAnimationFrame(animate); } animate(); }
function typeWriter(el, texts){ let i = 0, j = 0, isDeleting = false; function type(){ const current = texts[i]; if(isDeleting){ el.innerHTML = current.substring(0, j-1) + '<span style="border-right:3px solid var(--accent)"></span>';j-- } else{ el.innerHTML = current.substring(0, j+1) + '<span style="border-right:3px solid var(--accent)"></span>';j++ } if(!isDeleting && j === current.length){ isDeleting = true; setTimeout(type, 2500) } else if(isDeleting && j === 0){ isDeleting = false; i = (i + 1) % texts.length; setTimeout(type, 500) } else{ setTimeout(type, isDeleting? 40 : 80) } } type(); }
function scrollReveal(){ const observer = new IntersectionObserver(entries => { entries.forEach((entry, i) => { if(entry.isIntersecting){ setTimeout(()=>{entry.target.classList.add('revealed')}, i * 100) } }) }, {threshold: 0.1}); document.querySelectorAll('.section-title,.glass-card').forEach(el => { observer.observe(el); }); }
async function fetchAllProjects(){ const projectsContainer = document.getElementById('projects-grid'); if(!projectsContainer) return; let allRepos = [{ title: "PORTFOLIO WEBSITE", desc: "Website portfolio dengan tema maskulin dan animasi premium.", img: DATA.websiteScreenshot, link: "https://kangsad01.github.io" }]; for(const user of DATA.githubs){ try{ const res = await fetch('https://api.github.com/users/' + user + '/repos?sort=updated&per_page=10'); const repos = await res.json(); const mapped = repos.map(repo => ({ title: repo.name.toUpperCase(), desc: repo.description || "No description.", img: 'https://opengraph.githubassets.com/1/' + user + '/' + repo.name, link: repo.html_url })); allRepos = allRepos.concat(mapped); }catch(e){} } projectsContainer.innerHTML = allRepos.map((p,i) => `<div class="glass-card" style="transition-delay:${i*0.08}s"><img src="${p.img}" class="project-img" onerror="this.src='https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=600'"><h3 style="font-size:1.5rem;margin-bottom:1rem">${p.title}</h3><p style="margin-bottom:1.5rem">${p.desc}</p><a href="${p.link}" target="_blank" class="magnetic-btn">View Code</a></div>`).join(''); magneticButtons(); scrollReveal(); }
function Navbar(){ return `<nav><div class="logo">${DATA.nama}</div></nav>`; }
function Hero(){ return `<section class="hero"><div class="container"><h1 class="hero-title">${DATA.nama}</h1><p id="role-text" style="font-size:1.5rem;margin-bottom:2rem"></p><a href="#projects" class="magnetic-btn">View Projects</a></div></section>`; }
function Terminal(){ return `<section><div class="container"><div class="glass-card"><div style="display:flex;gap:8px;margin-bottom:1rem"><div style="width:12px;height:12px;border-radius:50%;background:#ff5f56"></div><div style="width:12px;height:12px;border-radius:50%;background:#ffbd2e"></div><div style="width:12px;height:12px;border-radius:50%;background:#27c93f"></div></div><div id="terminal-text" style="font-family:monospace;color:var(--accent)"></div></div></div></section>`; }
function About(){ const statsHTML = DATA.stats.map(s => `<div class="glass-card" style="text-align:center"><h3 style="font-size:3rem;color:var(--accent)">${s.number}+</h3><p style="font-weight:600">${s.label}</p></div>`).join(''); return `<section id="about"><div class="container"><h2 class="section-title">About Me</h2><div style="display:grid;grid-template-columns:1fr 2fr;gap:3rem;align-items:center"><img src="${DATA.foto}" style="width:100%;border-radius:20px;border:2px solid var(--accent)"><div><p style="font-size:1.2rem;line-height:1.8">${DATA.about}</p><div class="stats-grid" style="margin-top:2rem">${statsHTML}</div></div></div></div></section>`; }
function Projects(){ return `<section id="projects"><div class="container"><h2 class="section-title">Projects</h2><div class="project-grid" id="projects-grid"></div></div></section>`; }
function TechStack(){ const techHTML = DATA.tech.map((t,i) => `<div class="tech-card glass-card" style="transition-delay:${i*0.1}s"><img src="${t.icon}"><h3>${t.name}</h3></div>`).join(''); return `<section id="tech"><div class="container"><h2 class="section-title">Tech Stack</h2><div class="tech-grid">${techHTML}</div></section>`; }
function contactForm(){ return `<section id="contact"><div class="container"><h2 class="section-title">Contact</h2><div class="contact-grid"><div><div class="contact-item glass-card"><div class="contact-icon">📧</div><div><h3>Email</h3><p>${DATA.email}</p></div></div></div><form class="contact-form glass-card" onsubmit="alert('Message Sent!');return false"><input type="text" placeholder="Your Name" required><input type="email" placeholder="Your Email" required><textarea rows="5" placeholder="Your Message..." required></textarea><button type="submit" class="magnetic-btn">Send Message</button></form></div></div></section>` }
function Footer(){ return `<footer><div class="social-links"><a href="https://github.com/${DATA.githubs[0]}" target="_blank">GitHub</a></div><p>© 2026 ${DATA.nama} | Built with Code</p></footer>`; }
function init(){ initTheme(); document.body.innerHTML = Navbar() + Hero() + Terminal() + About() + Projects() + TechStack() + contactForm() + Footer(); liquidBackground(); particleBackground(); mouseGlow(); scrollProgress(); backToTop(); themeToggle(); autoMusic(); typeWriter(document.getElementById('role-text'), DATA.role); fetchAllProjects(); magneticButtons(); scrollReveal(); setTimeout(terminalType, 500); }
document.addEventListener('DOMContentLoaded', init);
